# Compliance keywords and their associated risk levels
COMPLIANCE_KEYWORDS = {
    "insider trading": "CRITICAL",
    "material non-public information": "CRITICAL",
    "front running": "CRITICAL",
    "market manipulation": "CRITICAL",
    "price manipulation": "CRITICAL",
    "spoofing": "CRITICAL",
    "layering": "CRITICAL",
    "wash trading": "CRITICAL",
    "anti-money laundering": "CRITICAL",
    "AML violation": "CRITICAL",
    "know your customer": "HIGH",
    "KYC violation": "HIGH",
    "customer due diligence": "HIGH",
    "CDD failure": "HIGH",
    "beneficial ownership": "HIGH",
    "sanctions violation": "CRITICAL",
    "OFAC violation": "CRITICAL",
    "sanctions evasion": "CRITICAL",
    "bribery": "CRITICAL",
    "corruption": "CRITICAL",
    "FCPA violation": "CRITICAL",
    "UK Bribery Act": "CRITICAL",
    "fraud": "CRITICAL",
    "financial fraud": "CRITICAL",
    "accounting fraud": "CRITICAL",
    "Ponzi scheme": "CRITICAL",
    "pyramid scheme": "CRITICAL",
    "LIBOR manipulation": "CRITICAL",
    "GDPR violation": "HIGH",
    "data privacy breach": "HIGH",
    "personal data leak": "HIGH",
    "MiFID II violation": "HIGH",
    "best execution": "HIGH",
    "transaction reporting": "MEDIUM",
    "EMIR violation": "HIGH",
    "derivatives reporting": "MEDIUM",
    "Dodd-Frank violation": "HIGH",
    "Volcker Rule": "HIGH",
    "proprietary trading": "HIGH",
    "conflict of interest": "HIGH",
    "fiduciary duty": "HIGH",
    "suitability requirement": "MEDIUM",
    "disclosure failure": "HIGH",
    "misrepresentation": "HIGH",
    "misleading statement": "HIGH",
    "market abuse": "CRITICAL",
    "MAR violation": "HIGH",
    "Basel III": "MEDIUM",
    "capital adequacy": "MEDIUM",
    "liquidity coverage ratio": "MEDIUM",
    "FATCA violation": "HIGH",
    "tax evasion": "CRITICAL",
    "CRS violation": "HIGH",
    "Sarbanes-Oxley": "HIGH",
    "SOX violation": "HIGH",
    "internal controls": "MEDIUM",
    "accounting irregularity": "HIGH",
    "ESG misrepresentation": "MEDIUM",
    "greenwashing": "MEDIUM",
    "sustainable finance": "LOW",
    "SFDR violation": "MEDIUM",
    "PSD2 violation": "MEDIUM",
    "strong customer authentication": "MEDIUM",
    "payment services": "LOW",
    "consumer protection": "MEDIUM",
    "unfair terms": "MEDIUM",
    "UCITS violation": "MEDIUM",
    "AIFMD violation": "MEDIUM",
    "benchmark manipulation": "CRITICAL",
    "IOSCO principles": "MEDIUM",
    "trade-based money laundering": "CRITICAL",
    "terrorist financing": "CRITICAL",
    "proliferation financing": "CRITICAL",
    "high-risk jurisdiction": "HIGH",
    "suspicious activity": "HIGH",
    "suspicious transaction": "HIGH",
    "regulatory reporting": "MEDIUM",
    "prudential requirements": "MEDIUM",
    "conduct risk": "MEDIUM",
    "cyber security breach": "HIGH",
    "operational resilience": "MEDIUM",
    "business continuity": "LOW",
    "outsourcing risk": "MEDIUM",
    "third-party risk": "MEDIUM",
    "whistleblower": "HIGH",
    "retaliation": "HIGH",
    "corporate governance": "MEDIUM",
    "board oversight": "MEDIUM",
    "remuneration policy": "MEDIUM",
    "excessive risk-taking": "HIGH",
    "compliance failure": "HIGH",
    "regulatory breach": "HIGH",
    "enforcement action": "HIGH",
    "consent order": "HIGH",
    "deferred prosecution": "HIGH",
    "cease and desist": "HIGH",
    "disgorgement": "HIGH",
    "civil penalty": "HIGH",
    "criminal prosecution": "CRITICAL"
}

# Risk level values
RISK_LEVELS = {
    "LOW": 0.3,
    "MEDIUM": 0.5,
    "HIGH": 0.7,
    "CRITICAL": 0.9
}
